FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npx pnpm install --global pnpm
RUN corepack enable
RUN apt-get update -y && apt-get install -y openssl libssl-dev
RUN npm install -g nx@19.8.4
#Install python3
#RUN apt-get install -y python3 python3-pip
#RUN apt-get install -y chromium

FROM base AS prod

WORKDIR /app
COPY pnpm-lock.yaml /app
WORKDIR /app
RUN pnpm fetch --prod

COPY . /app
#RUN npm install -g nx@19.8.4
RUN npx prisma generate --schema=apps/ts-rest-type-safety-app/prisma/schema.prisma
RUN pnpm run build

FROM base
COPY --from=prod /app/node_modules /app/node_modules
COPY --from=prod /app/dist /app/dist
#COPY --from=prod /app/package.json /app/package.json
EXPOSE 4200
WORKDIR /app
CMD [ "node", "dist/apps/ts-rest-type-safety-app/" ]
