services:
  nx-app-base:
    restart: always
    environment:
      - DEV_PLATFORM=DOCKER
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=mgh_user
      - DB_PASSWORD=mgh_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=mgh_user
      - MYSQL_PASSWORD=mgh_password
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  postgres_base:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mgh_user
      - POSTGRES_PASSWORD=mgh_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
